feat:support skip build command

diff --git a/commands/all-in-one b/commands/all-in-one
--- a/commands/all-in-one
+++ b/commands/all-in-one
@@ -37,10 +37,12 @@ core() {
     return 1
   fi
 
-  zmicro eunomia build
-  if [ "$?" != "0" ]; then
-    log::error "[$(timestamp)][docker][flow] failed to eunomia build."
-    return 1
+  if [ "$EUNOMIA_SKIP_BUILD_STAGE" != "true" ]; then
+    zmicro eunomia build
+      if [ "$?" != "0" ]; then
+        log::error "[$(timestamp)][docker][flow] failed to eunomia build."
+        return 1
+      fi
   fi
 
   zmicro eunomia deploy
