refact: move pre actions to pre

diff --git a/commands/all-in-one b/commands/all-in-one
--- a/commands/all-in-one
+++ b/commands/all-in-one
@@ -30,7 +30,7 @@ core() {
   fi
 
   export EUNOMIA_GIT_CHECKOUT_DIR=$EUNOMIA_BUILD_GIT_DIR
-    
+
   zmicro eunomia checkout
   if [ "$?" != "0" ]; then
     log::error "[$(timestamp)][docker][flow] failed to eunomia checkout."
@@ -39,35 +39,10 @@ core() {
 
   if [ "$EUNOMIA_SKIP_BUILD_STAGE" != "true" ]; then
     zmicro eunomia build
-      if [ "$?" != "0" ]; then
-        log::error "[$(timestamp)][docker][flow] failed to eunomia build."
-        return 1
-      fi
-  fi
-
-  if [ "$EUNOMIA_SKIP_BUILD_STAGE" = "true" ]; then
-     ## prepare
-      if [ -z "$EUNOMIA_BUILD_ID" ]; then
-        log::error "[$(timestamp)][build] EUNOMIA_BUILD_ID is required"
-        exit 1
-      fi
-
-      eunomia::show_version_info
-
-      log::info "[$(timestamp)][build] preparing ..."
-      eunomia::prepare
-      if [ "$?" != "0" ]; then
-        log::error "[$(timestamp)][build] failed to prepare"
-        exit 1
-      fi
-      ## env
-      log::info "[$(timestamp)] start to generate env shell at ${EUNOMIA_BUILD_ENV_SHELL} ..."
-      plugin::run_zx env_shell
-      if [ "$?" != "0" ]; then
-        log::error "[$(timestamp)] failed to generate env shell at ${EUNOMIA_BUILD_ENV_SHELL}."
-        return 1
-      fi
-      log::success "[$(timestamp)] succeed to generate env shell at ${EUNOMIA_BUILD_ENV_SHELL} ..."
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)][docker][flow] failed to eunomia build."
+      return 1
+    fi
   fi
 
   zmicro eunomia deploy
diff --git a/commands/pre b/commands/pre
--- a/commands/pre
+++ b/commands/pre
@@ -25,6 +25,31 @@ core() {
   log::info "[$(timestamp)][pre]  commit message: $EUNOMIA_GIT_COMMIT_MESSAGE"
   log::info "[$(timestamp)][pre]  commit author: $EUNOMIA_GIT_COMMIT_AUTHOR"
   log::info "[$(timestamp)][pre]  commit timestamp: $EUNOMIA_GIT_COMMIT_TIMESTAMP"
+
+  if [ "$EUNOMIA_SKIP_BUILD_STAGE" = "true" ]; then
+    ## prepare
+    if [ -z "$EUNOMIA_BUILD_ID" ]; then
+      log::error "[$(timestamp)][build] EUNOMIA_BUILD_ID is required"
+      exit 1
+    fi
+
+    eunomia::show_version_info
+
+    log::info "[$(timestamp)][build] preparing ..."
+    eunomia::prepare
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)][build] failed to prepare"
+      exit 1
+    fi
+    ## env
+    log::info "[$(timestamp)] start to generate env shell at ${EUNOMIA_BUILD_ENV_SHELL} ..."
+    plugin::run_zx env_shell
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)] failed to generate env shell at ${EUNOMIA_BUILD_ENV_SHELL}."
+      return 1
+    fi
+    log::success "[$(timestamp)] succeed to generate env shell at ${EUNOMIA_BUILD_ENV_SHELL} ..."
+  fi
 }
 
 run() {
