feat: support EUNOMIA_PROJECT_ENABLE_AUTO_TEST in all-in-one

diff --git a/commands/all-in-one b/commands/all-in-one
--- a/commands/all-in-one
+++ b/commands/all-in-one
@@ -51,6 +51,10 @@ core() {
 
   if [ "$EUNOMIA_PROJECT_ENABLE_AUTO_TEST" = "true" ]; then
     zmicro eunomia test
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)][docker][flow] failed to eunomia deploy."
+      return 1
+    fi
   fi
 
   zmicro eunomia post
