fix: exit code

diff --git a/commands/build b/commands/build
--- a/commands/build
+++ b/commands/build
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-# set -e
+# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
+set -o pipefail
 
 help() {
   echo "Usage:"
@@ -81,29 +82,13 @@ core() {
   fi
   log::success "[$(timestamp)] succeed to generate env shell at ${EUNOMIA_BUILD_ENV_SHELL} ..."
 
-  if [ -n "$FORCE_BUILD" ]; then
-    # build
-    log::info "[$(timestamp)][build] force building ..."
-    eunomia::build
-    if [ "$?" != "0" ]; then
-      log::error "[$(timestamp)][build] failed to build"
-      eunomia::task_queue_done >>/dev/null
-      exit 1
-    fi
-  else
-    log::info "[$(timestamp)][build] checking ${PLUGIN_EUNOMIA_EXPORT_RUNNER_IMAGE} ..."
-    if [ "$(eunomia::is_built)" != "true" ]; then
-      # build
-      log::info "[$(timestamp)][build] no cache, building ..."
-      eunomia::build
-      if [ "$?" != "0" ]; then
-        log::error "[$(timestamp)][build] failed to build (2)"
-        eunomia::task_queue_done >>/dev/null
-        exit 1
-      fi
-    else
-      log::info "[$(timestamp)][build] loading cache ..."
-    fi
+  # build
+  log::info "[$(timestamp)][build] start to build ..."
+  eunomia::build
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)][build] failed to build"
+    eunomia::task_queue_done >>/dev/null
+    exit 1
   fi
 
   log::info "[$(timestamp)][build] env PLUGIN_EUNOMIA_EXPORT_DISABLE: $PLUGIN_EUNOMIA_EXPORT_DISABLE"
diff --git a/commands/post b/commands/post
--- a/commands/post
+++ b/commands/post
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-# set -e
+# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
+set -o pipefail
 
 help() {
   echo "Usage:"
@@ -19,8 +20,12 @@ core() {
 run() {
   local log=$EUNOMIA_BUILD_DIR/post.log
   core "$@" 2>&1 | tee -a $log
-  if [ -f "$log" ]; then
+  if [ "$?" != "0" ]; then
     eunomia::hook_log $log
+    exit 1
+  else
+    eunomia::hook_log $log
+    exit 0
   fi
 }
 
diff --git a/commands/pre b/commands/pre
--- a/commands/pre
+++ b/commands/pre
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-# set -e
+# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
+set -o pipefail
 
 help() {
   echo "Usage:"
@@ -18,7 +19,7 @@ core() {
   log::info "[$(timestamp)][pre] build id: $EUNOMIA_BUILD_ID"
   log::info "[$(timestamp)][pre] executor: $EUNOMIA_BUILD_AUTHOR($EUNOMIA_BUILD_AUTHOR_EMAIL)"
   log::info "[$(timestamp)][pre] git info:"
-  log::info "[$(timestamp)][pre]  url: $EUNOMIA_GIT_REPO_URL"
+  log::info "[$(timestamp)][pre]  url: $EUNOMIA_GIT_REPOSITORY"
   log::info "[$(timestamp)][pre]  branch: $EUNOMIA_GIT_BRANCH"
   log::info "[$(timestamp)][pre]  commit hash: $EUNOMIA_GIT_COMMIT"
   log::info "[$(timestamp)][pre]  commit message: $EUNOMIA_GIT_COMMIT_MESSAGE"
@@ -29,8 +30,12 @@ core() {
 run() {
   local log=$EUNOMIA_BUILD_DIR/pre.log
   core "$@" 2>&1 | tee -a $log
-  if [ -f "$log" ]; then
+  if [ "$?" != "0" ]; then
     eunomia::hook_log $log
+    exit 1
+  else
+    eunomia::hook_log $log
+    exit 0
   fi
 }
 
