refactor: better env

diff --git a/commands/build b/commands/build
--- a/commands/build
+++ b/commands/build
@@ -13,13 +13,13 @@ core() {
     exit 0
   fi
 
-  if [ "$(zmicro fn os::is_docker)" != "true" ]; then
-    log::error "[$(timestamp)][build] the command(flow) can only be run in docker"
-    exit 1
-  fi
+  # if [ "$(zmicro fn os::is_docker)" != "true" ]; then
+  #   log::error "[$(timestamp)][build] the command(flow) can only be run in docker"
+  #   exit 1
+  # fi
 
-  if [ -z "$PLUGIN_EUNOMIA_BUILD_ID" ]; then
-    log::error "[$(timestamp)][build] PLUGIN_EUNOMIA_BUILD_ID is required"
+  if [ -z "$EUNOMIA_BUILD_ID" ]; then
+    log::error "[$(timestamp)][build] EUNOMIA_BUILD_ID is required"
     exit 1
   fi
 
@@ -83,11 +83,6 @@ core() {
     done
   fi
 
-  # # @TODO if no user found, do something
-  # if [ -z "$PLUGIN_EUNOMIA_BUILD_AUTHOR_EMAIL" ]; then
-  #   export FORCE_BUILD="true"
-  # fi
-
   if [ -n "$FORCE_BUILD" ]; then
     # build
     log::info "[$(timestamp)][build] force building ..."
@@ -131,7 +126,30 @@ core() {
 }
 
 run() {
-  core $@
+  if [ -z "$EUNOMIA_BUILD_ID" ]; then
+    log::error "[$(timestamp)][docker][flow] EUNOMIA_BUILD_ID is required"
+    exit 1
+  fi
+
+  # must mkdir or tee log file not found in docker flow
+  if [ ! -d "$EUNOMIA_BUILD_ID_DIR" ]; then
+    mkdir -p $EUNOMIA_BUILD_ID_DIR
+  fi
+
+  # start
+  eunomia::hook_start
+
+  core "$@" | tee -a $EUNOMIA_BUILD_ID_LOG
+  # end
+  if [ "$?" != "0" ]; then
+    eunomia::hook_failed
+    log::info "[$(timestamp)][docker_flow] flow failed."
+    return 1
+  else
+    eunomia::hook_succeed
+    log::info "[$(timestamp)][docker_flow] flow succeed."
+    return 0
+  fi
 }
 
-run $@
+run "$@"
diff --git a/commands/docker/flow b/commands/docker/flow
--- a/commands/docker/flow
+++ b/commands/docker/flow
@@ -16,47 +16,41 @@ core() {
 
   eunomia::show_version_info
 
+  # @TODO avoid to re base64 decode
+  export FLOW_CI=false
+
   if [ -n "$EUNOMIA_GIT_REPOSITORY" ] && [ -n "$EUNOMIA_GIT_BRANCH" ] && [ -n "$EUNOMIA_GIT_COMMIT" ]; then
     export EUNOMIA_GIT_CHECKOUT_DIR=$(os::tmp_dir)
     export PLUGIN_EUNOMIA_DOWNLOAD_PKG="${PLUGIN_EUNOMIA_TMP_DIR}/$(os::random_string 8).tar.gz"
-
-    log::info "[$(timestamp)][docker][flow] checkouting with $EUNOMIA_GIT_REPOSITORY at $EUNOMIA_GIT_BRANCH ..."
-    eunomia::checkout
+    
+    zmicro eunomia checkout
     if [ "$?" != "0" ]; then
-      log::error "[$(timestamp)][docker][flow] failed to checkout git repo."
+      log::error "[$(timestamp)][docker][flow] failed to eunomia checkout."
       return 1
     fi
 
-    log::success "[$(timestamp)][docker][flow] succeed to checkout git repo."
-    
-    log::info "[$(timestamp)][docker][flow] creating DOWNLOAD_PKG at $PLUGIN_EUNOMIA_DOWNLOAD_PKG ..."
+    log::info "[$(timestamp)][checkout] creating DOWNLOAD_PKG at $PLUGIN_EUNOMIA_DOWNLOAD_PKG ..."
     cd $EUNOMIA_GIT_CHECKOUT_DIR
     tar -zcvf $PLUGIN_EUNOMIA_DOWNLOAD_PKG ./ >>/dev/null
     if [ "$?" != "0" ]; then
-      log::error "[$(timestamp)][docker][flow] failed to create DOWNLOAD_PKG."
+      log::error "[$(timestamp)][checkout] failed to create DOWNLOAD_PKG."
       return 1
     fi
     cd -
   fi
 
-  echo "PLUGIN_EUNOMIA_BUILD_ID_DIR: $PLUGIN_EUNOMIA_BUILD_ID_DIR"
-  echo "PLUGIN_EUNOMIA_DOWNLOAD_PKG: $PLUGIN_EUNOMIA_DOWNLOAD_PKG"
+  log::info "[$(timestamp)] EUNOMIA_BUILD_ID_DIR: $EUNOMIA_BUILD_ID_DIR"
+  log::info "[$(timestamp)] PLUGIN_EUNOMIA_DOWNLOAD_PKG: $PLUGIN_EUNOMIA_DOWNLOAD_PKG"
 
-  eunomia::docker_flow
+  zmicro eunomia build
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)][docker][flow] failed to eunomia build."
+    return 1
+  fi
 }
 
 run() {
-  if [ -z "$PLUGIN_EUNOMIA_BUILD_ID" ]; then
-    log::error "[$(timestamp)][docker][flow] PLUGIN_EUNOMIA_BUILD_ID is required"
-    exit 1
-  fi
-
-  # must mkdir or tee log file not found in docker flow
-  if [ ! -d "$PLUGIN_EUNOMIA_BUILD_ID_DIR" ]; then
-    mkdir -p $PLUGIN_EUNOMIA_BUILD_ID_DIR
-  fi
-
-  core $@ | tee -a $PLUGIN_EUNOMIA_BUILD_ID_LOG
+  core "$@"
 }
 
-run $@
+run "$@"
