feat: support webhook trigger start/succeed/failed

diff --git a/commands/flow b/commands/flow
--- a/commands/flow
+++ b/commands/flow
@@ -13,6 +13,27 @@ core() {
     exit 0
   fi
 
+  if [ -z "$PLUGIN_EUNOMIA_BUILD_ID" ]; then
+    log::error "[$(timestamp)][flow] PLUGIN_EUNOMIA_BUILD_ID is required"
+    exit 1
+  fi
+  
+  if [ -z "$PLUGIN_EUNOMIA_GIT_REPO_NAME" ]; then
+    log::error "[$(timestamp)][flow] PLUGIN_EUNOMIA_GIT_REPO_NAME is required"
+    exit 1
+  fi
+
+  if [ -z "$PLUGIN_EUNOMIA_GIT_REPO_PKG" ]; then
+    log::error "[$(timestamp)][flow] PLUGIN_EUNOMIA_GIT_REPO_PKG is required"
+    exit 1
+  fi
+
+  echo $PLUGIN_EUNOMIA_GIT_REPO_PKG | grep $PLUGIN_EUNOMIA_GIT_REPO_PKG_TMP_DIR >> /dev/null 2>&1
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)][flow] PLUGIN_EUNOMIA_GIT_REPO_PKG(${PLUGIN_EUNOMIA_GIT_REPO_PKG}) must be starts with ${PLUGIN_EUNOMIA_GIT_REPO_PKG_TMP_DIR}"
+    exit 1
+  fi
+
   log::info "[$(timestamp)][flow] preparing ..."
   eunomia::prepare
 
