refactor

diff --git a/commands/docker/flow b/commands/docker/flow
--- a/commands/docker/flow
+++ b/commands/docker/flow
@@ -14,18 +14,24 @@ core() {
     exit 0
   fi
 
+  echo "PLUGIN_EUNOMIA_BUILD_ID_DIR: $PLUGIN_EUNOMIA_BUILD_ID_DIR"
+  echo "PLUGIN_EUNOMIA_DOWNLOAD_GIT_PKG: $PLUGIN_EUNOMIA_DOWNLOAD_GIT_PKG"
+
   eunomia::docker_flow
 }
 
 run() {
+  if [ -z "$PLUGIN_EUNOMIA_BUILD_ID" ]; then
+    log::error "[$(timestamp)][flow] PLUGIN_EUNOMIA_BUILD_ID is required"
+    exit 1
+  fi
+
   # must mkdir or tee log file not found in docker flow
   if [ ! -d "$PLUGIN_EUNOMIA_BUILD_ID_DIR" ]; then
     mkdir -p $PLUGIN_EUNOMIA_BUILD_ID_DIR
   fi
 
-  echo "PLUGIN_EUNOMIA_BUILD_ID_DIR: $PLUGIN_EUNOMIA_BUILD_ID_DIR"
-
-  core $@ | tee -a $PLUGIN_EUNOMIA_BUILD_LOG
+  core $@ | tee -a $PLUGIN_EUNOMIA_BUILD_ID_LOG
 }
 
 run $@
diff --git a/core/prepare b/core/prepare
--- a/core/prepare
+++ b/core/prepare
@@ -7,32 +7,15 @@ eunomia::prepare() {
     return 1
   fi
 
-  if [ -z "$PLUGIN_EUNOMIA_GIT_REPO_PKG" ]; then
-    log::error "[prepare] PLUGIN_EUNOMIA_GIT_REPO_PKG is required"
+  if [ -z "$PLUGIN_EUNOMIA_DOWNLOAD_GIT_PKG" ]; then
+    log::error "[prepare] PLUGIN_EUNOMIA_DOWNLOAD_GIT_PKG is required"
     return 1
   fi
 
-  if [ ! -f "$PLUGIN_EUNOMIA_GIT_REPO_PKG" ]; then
-    log::error "[prepare] file($PLUGIN_EUNOMIA_GIT_REPO_PKG) is not found"
+  if [ ! -f "$PLUGIN_EUNOMIA_DOWNLOAD_GIT_PKG" ]; then
+    log::error "[prepare] file($PLUGIN_EUNOMIA_DOWNLOAD_GIT_PKG) is not found"
     return 1
   fi
-
-  export PLUGIN_EUNOMIA_GIT_REPO_DIR=$PLUGIN_EUNOMIA_GIT_DIR/$PLUGIN_EUNOMIA_BUILD_ID
-  if [ ! -d "$PLUGIN_EUNOMIA_GIT_REPO_DIR" ]; then
-    mkdir -p $PLUGIN_EUNOMIA_GIT_REPO_DIR
-  fi
-
-  export PLUGIN_EUNOMIA_GIT_DOT_ENV=$PLUGIN_EUNOMIA_GIT_REPO_DIR/.eunomia
-  export PLUGIN_EUNOMIA_GIT_REPO_PKG=$PLUGIN_EUNOMIA_GIT_REPO_PKG
-
-  # EXPORT
-  export PLUGIN_EUNOMIA_EXPORT_ID_DIR=${PLUGIN_EUNOMIA_EXPORT_DIR}/$PLUGIN_EUNOMIA_BUILD_ID
-  export PLUGIN_EUNOMIA_EXPORT_ID_PKG=${PLUGIN_EUNOMIA_EXPORT_ID_DIR}.tar.gz
-
-  #
-  export PLUGIN_EUNOMIA_RUNNER_NAME=${PLUGIN_EUNOMIA_DOCKER_CONTAINER_PREFIX}${PLUGIN_EUNOMIA_BUILD_ID}
-  # 指定容器构建产物目录，默认是 /var/www/html
-  export PLUGIN_EUNOMIA_RUNNER_DIST_DIR=${PLUGIN_EUNOMIA_RUNNER_DIST_DIR:-"/var/www/html"}
 
   if [ ! -d "$PLUGIN_EUNOMIA_BUILD_ID_DIR" ]; then
     mkdir -p $PLUGIN_EUNOMIA_BUILD_ID_DIR
@@ -53,75 +36,37 @@ eunomia::prepare() {
     return 1
   fi
 
-  # @TODO PLUGIN_EUNOMIA_GIT_REPO_PKG 很可能是固定路径，这里用于快速备份，避免被后续部署覆盖
-  if [ ! -f "$PLUGIN_EUNOMIA_BUILD_ID_PKG" ]; then
-    cp $PLUGIN_EUNOMIA_GIT_REPO_PKG $PLUGIN_EUNOMIA_BUILD_ID_PKG
-  fi
+  # @TODO PLUGIN_EUNOMIA_DOWNLOAD_GIT_PKG 很可能是固定路径，这里用于快速备份，避免被后续部署覆盖
+  cp $PLUGIN_EUNOMIA_DOWNLOAD_GIT_PKG $PLUGIN_EUNOMIA_BUILD_ID_PKG
+  # PLUGIN_EUNOMIA_DOWNLOAD_GIT_PKG 使命完成，后续使用 PLUGIN_EUNOMIA_BUILD_ID_PKG
 
   # Extract Git Repo
-  if [ -z "$(ls $PLUGIN_EUNOMIA_GIT_REPO_DIR)" ]; then
-    tar -zxvf $PLUGIN_EUNOMIA_BUILD_ID_PKG -C $PLUGIN_EUNOMIA_GIT_REPO_DIR >>/dev/null
+  if [ ! -d "$PLUGIN_EUNOMIA_BUILD_GIT_DIR" ]; then
+    mkdir -p $PLUGIN_EUNOMIA_BUILD_GIT_DIR
+    tar -zxvf $PLUGIN_EUNOMIA_BUILD_ID_PKG -C $PLUGIN_EUNOMIA_BUILD_GIT_DIR >>/dev/null
   fi
+  # PLUGIN_EUNOMIA_BUILD_ID_PKG 使命完成
 
-  # check env .eunomia
-  # echo "check env .eunomia: $PLUGIN_EUNOMIA_GIT_DOT_ENV"
-  if [ -f "$PLUGIN_EUNOMIA_GIT_DOT_ENV" ]; then
-    log::info "[prepare] load user env .eunomia: $PLUGIN_EUNOMIA_GIT_DOT_ENV"
+  # Go to Git Repo Dir
+  cd $PLUGIN_EUNOMIA_BUILD_GIT_DIR
 
-    cat $PLUGIN_EUNOMIA_GIT_DOT_ENV
+  # @LOAD Git Repo Env
+  # echo "check env .eunomia: $PLUGIN_EUNOMIA_BUILD_GIT_DOT_ENV"
+  if [ -f "$PLUGIN_EUNOMIA_BUILD_GIT_DOT_ENV" ]; then
+    log::info "[prepare] load user env .eunomia: $PLUGIN_EUNOMIA_BUILD_GIT_DOT_ENV"
 
-    dotenv::load $PLUGIN_EUNOMIA_GIT_DOT_ENV
+    cat $PLUGIN_EUNOMIA_BUILD_GIT_DOT_ENV
+
+    dotenv::load $PLUGIN_EUNOMIA_BUILD_GIT_DOT_ENV
     if [ "$?" != "0" ]; then
-      log::error "[prepare] failed to load repo env($PLUGIN_EUNOMIA_GIT_DOT_ENV)"
+      log::error "[prepare] failed to load repo env($PLUGIN_EUNOMIA_BUILD_GIT_DOT_ENV)"
       return 1
     fi
   fi
 
-  # Dockerfile env
-  # support custom PLUGIN_EUNOMIA_RUNNER_DIST_DIR and others
-  if [ -f "${PLUGIN_EUNOMIA_GIT_REPO_DOCKERFILE_ENV}" ]; then
-    log::info "[prepare] load docker env(${PLUGIN_EUNOMIA_GIT_REPO_DOCKERFILE_ENV})"
-
-    cat $PLUGIN_EUNOMIA_GIT_REPO_DOCKERFILE_ENV
-
-    dotenv::load $PLUGIN_EUNOMIA_GIT_REPO_DOCKERFILE_ENV
-    if [ "$?" != "0" ]; then
-      log::error "[prepare] failed to load dockerfile .eunomia($PLUGIN_EUNOMIA_GIT_REPO_DOCKERFILE_ENV)"
-      return 1
-    fi
-  fi
-
-  # After Load Env
-
-  # @ Repo
-  export PLUGIN_EUNOMIA_GIT_REPO_URL=${PLUGIN_EUNOMIA_GIT_REPO_URL:-$EUNOMIA_GIT_REPO_URL}
-  export PLUGIN_EUNOMIA_GIT_REPO_NAME=${PLUGIN_EUNOMIA_GIT_REPO_NAME:-$EUNOMIA_GIT_REPO_NAME}
-  export PLUGIN_EUNOMIA_GIT_BRANCH=${PLUGIN_EUNOMIA_GIT_BRANCH:-$EUNOMIA_GIT_BRANCH}
-  export PLUGIN_EUNOMIA_GIT_COMMIT_ACTOR=${PLUGIN_EUNOMIA_GIT_COMMIT_ACTOR:-$EUNOMIA_GIT_COMMIT_ACTOR}
-  export PLUGIN_EUNOMIA_GIT_COMMIT=${PLUGIN_EUNOMIA_GIT_COMMIT:-$EUNOMIA_GIT_COMMIT}
-  export PLUGIN_EUNOMIA_GIT_COMMIT_TIMESTAMP=${PLUGIN_EUNOMIA_GIT_COMMIT_TIMESTAMP:-$EUNOMIA_GIT_COMMIT_TIMESTAMP}
-  if [ -z "$PLUGIN_EUNOMIA_GIT_REPO_NAME" ]; then
-    log::error "[eunomia::build] PLUGIN_EUNOMIA_GIT_REPO_NAME is required (cannot found in dot env .eunomia)"
-    return 1
-  fi
-
-  if [ -z "$(echo $PLUGIN_EUNOMIA_GIT_REPO_NAME | awk -F '/' '{print $2}')" ]; then
-    log::error "[eunomia::build] PLUGIN_EUNOMIA_GIT_REPO_NAME is invalid, must be in the format of 'owner/repo'"
-    return 1
-  fi
-
-  # Dockerfile
-  export PLUGIN_EUNOMIA_GIT_REPO_DOCKERFILE=${PLUGIN_EUNOMIA_DOCKERFILES_DIR}/${PLUGIN_EUNOMIA_GIT_REPO_NAME}/Dockerfile
-  export PLUGIN_EUNOMIA_GIT_REPO_DOCKERFILE_ENV=${PLUGIN_EUNOMIA_DOCKERFILES_DIR}/${PLUGIN_EUNOMIA_GIT_REPO_NAME}/.eunomia
-  if [ ! -f "$PLUGIN_EUNOMIA_GIT_REPO_DOCKERFILE" ]; then
-    log::error "[eunomia::build] Dockerfile not found at for $PLUGIN_EUNOMIA_GIT_REPO_NAME"
-    return 1
-  fi
-
-  # @TODO USER
-  export PLUGIN_EUNOMIA_EXECUTOR_EMAIL=${PLUGIN_EUNOMIA_EXECUTOR_EMAIL:-$EUNOMIA_EXECUTOR_EMAIL}
-  export PLUGIN_EUNOMIA_EXECUTOR_NAME=${PLUGIN_EUNOMIA_EXECUTOR_NAME:-$EUNOMIA_EXECUTOR_NAME}
-  export PLUGIN_EUNOMIA_EXECUTOR_ID=${PLUGIN_EUNOMIA_EXECUTOR_ID:-$EUNOMIA_EXECUTOR_ID}
+  # USER
+  export PLUGIN_EUNOMIA_BUILD_AUTHOR=${PLUGIN_EUNOMIA_BUILD_AUTHOR:-$EUNOMIA_AUTHOR}
+  export PLUGIN_EUNOMIA_BUILD_AUTHOR_EMAIL=${PLUGIN_EUNOMIA_BUILD_AUTHOR_EMAIL:-$EUNOMIA_AUTHOR_EMAIL}
 
   # @TODO Eunomia Manager
   export PLUGIN_EUNOMIA_PROJECT_ID=${PLUGIN_EUNOMIA_PROJECT_ID:-$EUNOMIA_PROJECT_ID}
@@ -143,6 +88,40 @@ eunomia::prepare() {
   export PLUGIN_EUNOMIA_SUCCEED_HOOK=${PLUGIN_EUNOMIA_SUCCEED_HOOK:-"$EUNOMIA_SUCCEED_HOOK"}
   export PLUGIN_EUNOMIA_FAILED_HOOK=${PLUGIN_EUNOMIA_FAILED_HOOK:-"$EUNOMIA_FAILED_HOOK"}
 
+  # @ Repo
+  GIT_REPO_NAMESPACE=$(git config --get remote.origin.url | awk -F '/' '{print $4}')
+  GIT_REPO_BASE_NAME=$(git config --get remote.origin.url | awk -F '/' '{print $5}' | awk -F '.git' '{print $1}')
+  GIT_COMMIT=$(git rev-parse HEAD)
+  export PLUGIN_EUNOMIA_GIT_REPO_URL=$(git config --get remote.origin.url)
+  export PLUGIN_EUNOMIA_GIT_REPO_NAME=${GIT_REPO_NAMESPACE}/${GIT_REPO_BASE_NAME}
+  export PLUGIN_EUNOMIA_GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
+  export PLUGIN_EUNOMIA_GIT_COMMIT=$(git rev-parse HEAD)
+  export PLUGIN_EUNOMIA_GIT_COMMIT_MESSAGE=$(git log --format=%B -n 1 $GIT_COMMIT)
+  export PLUGIN_EUNOMIA_GIT_COMMIT_AUTHOR=$(git show -s --format='%ae' $GIT_COMMIT)
+  export PLUGIN_EUNOMIA_GIT_COMMIT_TIMESTAMP="$(git show -s --format=%cd --date='format:%Y-%m-%d_%H:%M:%S')"
+
+  # @COPY Dockerfile
+  export PLUGIN_EUNOMIA_DOCKERFILE_FOR_GIT_REPO=${PLUGIN_EUNOMIA_DOCKERFILES_DIR}/${PLUGIN_EUNOMIA_GIT_REPO_NAME}/Dockerfile
+  export PLUGIN_EUNOMIA_DOCKERFILE_ENV_FOR_GIT_REPO=${PLUGIN_EUNOMIA_DOCKERFILES_DIR}/${PLUGIN_EUNOMIA_GIT_REPO_NAME}/.eunomia
+  if [ ! -f "$PLUGIN_EUNOMIA_DOCKERFILE_FOR_GIT_REPO" ]; then
+    log::error "[eunomia::build] Dockerfile not found at for $PLUGIN_EUNOMIA_GIT_REPO_NAME"
+    return 1
+  fi
+
+  # @LOAD Dockerfile Repo Env
+  # support custom PLUGIN_EUNOMIA_EXPORT_RUNNER_DIST_DIR and others
+  if [ -f "${PLUGIN_EUNOMIA_DOCKERFILE_ENV_FOR_GIT_REPO}" ]; then
+    log::info "[prepare] load dockerfile env(${PLUGIN_EUNOMIA_DOCKERFILE_ENV_FOR_GIT_REPO})"
+
+    cat $PLUGIN_EUNOMIA_DOCKERFILE_ENV_FOR_GIT_REPO
+
+    dotenv::load $PLUGIN_EUNOMIA_DOCKERFILE_ENV_FOR_GIT_REPO
+    if [ "$?" != "0" ]; then
+      log::error "[prepare] failed to load dockerfile .eunomia($PLUGIN_EUNOMIA_DOCKERFILE_ENV_FOR_GIT_REPO)"
+      return 1
+    fi
+  fi
+
   ##############
   ##############
   if [ -n "$PLUGIN_EUNOMIA_BUILD_HASH" ]; then
@@ -154,7 +133,7 @@ eunomia::prepare() {
   # plugin-pipeline
   export PIPELINE_BUILD_ID=${PLUGIN_EUNOMIA_BUILD_ID}
   export PIPELINE_BUILD_CONTEXT=$PLUGIN_EUNOMIA_BUILD_ID_DIR
-  export PIPELINE_GIT_REPOSITORY_DIR=$PLUGIN_EUNOMIA_GIT_REPO_DIR
+  export PIPELINE_GIT_REPOSITORY_DIR=$PLUGIN_EUNOMIA_BUILD_GIT_DIR
   export PIPELINE_DOCKER_REGISTRY=$PLUGIN_EUNOMIA_DOCKER_REGISTRY
   export PIPELINE_IMAGE_NAME=$PLUGIN_EUNOMIA_GIT_REPO_NAME
   export PIPELINE_IMAGE_TAGS=commit_${PLUGIN_EUNOMIA_BUILD_HASH:-${PLUGIN_EUNOMIA_BUILD_ID}}
@@ -162,7 +141,7 @@ eunomia::prepare() {
   ##############
 
   if [ -n "$PIPELINE_IMAGE_TAGS" ]; then
-    export PLUGIN_EUNOMIA_RUNNER_IMAGE=$PLUGIN_EUNOMIA_DOCKER_REGISTRY/$PIPELINE_IMAGE_NAME:$PIPELINE_IMAGE_TAGS
+    export PLUGIN_EUNOMIA_EXPORT_RUNNER_IMAGE=$PLUGIN_EUNOMIA_DOCKER_REGISTRY/$PIPELINE_IMAGE_NAME:$PIPELINE_IMAGE_TAGS
   fi
 }
 
