fix: docker flow log, because the origin log generated by pipeline plugin, if not running pipeline, you cannot get log

diff --git a/commands/docker/flow b/commands/docker/flow
--- a/commands/docker/flow
+++ b/commands/docker/flow
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-# set -e
+# fix tee modify the exit code: https://stackoverflow.com/questions/6871859/piping-command-output-to-tee-but-also-save-exit-code-of-command
+set -o pipefail
 
 help() {
   echo "Usage:"
@@ -57,7 +58,7 @@ core() {
 }
 
 run() {
-  core $@
+  core $@ | tee -a $PLUGIN_EUNOMIA_BUILD_LOG
 }
 
 run $@
