fix: prepare first

diff --git a/core/build b/core/build
--- a/core/build
+++ b/core/build
@@ -1,9 +1,15 @@
 #!/bin/bash
 
 eunomia::build() {
-  # eunomia::prepare
-  eunomia::prepare
+  if [ -z "$PLUGIN_EUNOMIA_GIT_REPO_DIR" ]; then
+    log::error "[eunomia::build] PLUGIN_EUNOMIA_GIT_REPO_DIR is required"
+    exit 1
+  fi
 
+  if [ ! -d "$PLUGIN_EUNOMIA_GIT_REPO_DIR" ]; then
+    log::error "[eunomia::build] you must run prepare first"
+    exit 1
+  fi
   # Dockerfile
   cp ${PLUGIN_DIR}/config/docker/Dockerfile $PLUGIN_EUNOMIA_GIT_REPO_DIR
 
