refact: export custom

diff --git a/core/export b/core/export
--- a/core/export
+++ b/core/export
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 eunomia::export() {
-  if [ -z "$PLUGIN_EUNOMIA_EXPORT_DIR" ]; then
-    log::error "[eunomia::export] PLUGIN_EUNOMIA_EXPORT_DIR is required"
+  if [ -z "$PLUGIN_EUNOMIA_EXPORT_ID_DIR" ]; then
+    log::error "[eunomia::export] PLUGIN_EUNOMIA_EXPORT_ID_DIR is required"
     exit 1
   fi
 
@@ -11,13 +11,13 @@ eunomia::export() {
     exit 1
   fi
 
-  # if [ ! -d "$PLUGIN_EUNOMIA_EXPORT_DIR" ]; then
-  #   log::error "[eunomia::export] PLUGIN_EUNOMIA_EXPORT_DIR(${PLUGIN_EUNOMIA_EXPORT_DIR}) is not a directory"
+  # if [ ! -d "$PLUGIN_EUNOMIA_EXPORT_ID_DIR" ]; then
+  #   log::error "[eunomia::export] PLUGIN_EUNOMIA_EXPORT_ID_DIR(${PLUGIN_EUNOMIA_EXPORT_ID_DIR}) is not a directory"
   #   exit 1
   # fi
 
   # clean
-  rm -rf $PLUGIN_EUNOMIA_EXPORT_DIR
+  rm -rf $PLUGIN_EUNOMIA_EXPORT_ID_DIR
 
   docker run -d --name $PLUGIN_EUNOMIA_RUNNER_NAME $PLUGIN_EUNOMIA_RUNNER_IMAGE >> /dev/null 2>&1
   if [ "$?" != "0" ]; then
@@ -25,13 +25,26 @@ eunomia::export() {
     exit 1
   fi
   
-  docker cp $PLUGIN_EUNOMIA_RUNNER_NAME:/var/www/html $PLUGIN_EUNOMIA_EXPORT_DIR
+  docker cp $PLUGIN_EUNOMIA_RUNNER_NAME:/var/www/html $PLUGIN_EUNOMIA_EXPORT_ID_DIR
   if [ "$?" != "0" ]; then
     log::error "[eunomia::export] failed to export when copying from runner"
     exit 1
   fi
+  tar -zcvf $PLUGIN_EUNOMIA_EXPORT_ID_PKG $PLUGIN_EUNOMIA_EXPORT_ID_DIR
+  if [ "$?" != "0" ]; then
+    log::error "[eunomia::export] failed to export when compressing"
+    exit 1
+  fi
+  rm -rf $PLUGIN_EUNOMIA_EXPORT_ID_DIR
 
   docker rm -f $PLUGIN_EUNOMIA_RUNNER_NAME >> /dev/null 2>&1
+
+  if [ -n "$PLUGIN_EUNOMIA_EXPORT_DIST" ]; then
+    log::info "[eunomia::export] exporting to $PLUGIN_EUNOMIA_EXPORT_DIST"
+    cp $PLUGIN_EUNOMIA_EXPORT_ID_PKG $PLUGIN_EUNOMIA_EXPORT_DIST
+  fi
+
+  log::info "[eunomia::export] done"
 }
 
 export -f eunomia::export
