chore: add env PLUGIN_TA_MULTIVERSE_BUILD_ID required

diff --git a/core/prepare b/core/prepare
--- a/core/prepare
+++ b/core/prepare
@@ -2,31 +2,36 @@
 
 # gvm::current gets the current version of Go
 ta-multiverse::prepare() {
-  # HASH
-  export PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH=$(md5sum $PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG | awk -F " " '{print $1}')
-  export PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR=${PLUGIN_TA_MULTIVERSE_BUILD_DIR}/${PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH}
-  export PLUGIN_TA_MULTIVERSE_GIT_REPO_DIR=$PLUGIN_TA_MULTIVERSE_GIT_DIR/$PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH
+  # # HASH
+  # # export PLUGIN_TA_MULTIVERSE_BUILD_HASH=$(md5sum $PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG | awk -F " " '{print $1}')
+  # export PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR=${PLUGIN_TA_MULTIVERSE_BUILD_DIR}/${PLUGIN_TA_MULTIVERSE_BUILD_ID}
+  # export PLUGIN_TA_MULTIVERSE_GIT_REPO_DIR=$PLUGIN_TA_MULTIVERSE_GIT_DIR/$PLUGIN_TA_MULTIVERSE_BUILD_ID
 
-  # PIPELINE
-  export PIPELINE_BUILD_CONTEXT=$PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR
-  export PIPELINE_GIT_REPOSITORY_DIR=$PLUGIN_TA_MULTIVERSE_GIT_REPO_DIR
-  export PIPELINE_DOCKER_REGISTRY=$PLUGIN_TA_MULTIVERSE_DOCKER_REGISTRY
-  export PIPELINE_IMAGE_NAME=$PLUGIN_TA_MULTIVERSE_GIT_REPO_NAME
-  export PIPELINE_IMAGE_TAGS=build_${PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH}
+  # # PIPELINE
+  # export PIPELINE_BUILD_CONTEXT=$PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR
+  # export PIPELINE_GIT_REPOSITORY_DIR=$PLUGIN_TA_MULTIVERSE_GIT_REPO_DIR
+  # export PIPELINE_DOCKER_REGISTRY=$PLUGIN_TA_MULTIVERSE_DOCKER_REGISTRY
+  # export PIPELINE_IMAGE_NAME=$PLUGIN_TA_MULTIVERSE_GIT_REPO_NAME
+  # export PIPELINE_IMAGE_TAGS=build_${PLUGIN_TA_MULTIVERSE_BUILD_ID}
 
-  # EXPORT
-  export PLUGIN_TA_MULTIVERSE_EXPORT_DIR=${PLUGIN_TA_MULTIVERSE_EXPORT_DIR:-"$PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR/dist"}
-  #
-  export PLUGIN_TA_MULTIVERSE_RUNNER_NAME=zpipeline_${PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH}
-  export PLUGIN_TA_MULTIVERSE_RUNNER_IMAGE=$PLUGIN_TA_MULTIVERSE_DOCKER_REGISTRY/$PIPELINE_IMAGE_NAME:$PIPELINE_IMAGE_TAGS
+  # # EXPORT
+  # export PLUGIN_TA_MULTIVERSE_EXPORT_DIR=${PLUGIN_TA_MULTIVERSE_EXPORT_DIR:-"$PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR/dist"}
+  # #
+  # export PLUGIN_TA_MULTIVERSE_RUNNER_NAME=zpipeline_${PLUGIN_TA_MULTIVERSE_BUILD_ID}
+  # export PLUGIN_TA_MULTIVERSE_RUNNER_IMAGE=$PLUGIN_TA_MULTIVERSE_DOCKER_REGISTRY/$PIPELINE_IMAGE_NAME:$PIPELINE_IMAGE_TAGS
+
+  if [ -z "$PLUGIN_TA_MULTIVERSE_BUILD_ID" ]; then
+    log::error "[prepare] PLUGIN_TA_MULTIVERSE_BUILD_ID is required"
+    exit 1
+  fi
 
   if [ -z "$PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG" ]; then
-    log::info "PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG is required"
+    log::error "[prepare] PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG is required"
     exit 1
   fi
 
   if  [ ! -f "$PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG" ]; then
-    log::info "PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG($PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG) is not a file"
+    log::error "[prepare] PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG($PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG) is not a file"
     exit 1
   fi
 
