fix: build

diff --git a/core/prepare b/core/prepare
--- a/core/prepare
+++ b/core/prepare
@@ -2,28 +2,39 @@
 
 # gvm::current gets the current version of Go
 ta-multiverse::prepare() {
-  export GIT_REPO_NAME=${GIT_REPO_NAME:-"thinking-frontend/ta-multiverse"}
-  export GIT_REPO_PKG=${GIT_REPO_PKG:-"/build/flow/ta-multiverse.tgz"}
-  export DOCKER_REGISTRY=${DOCKER_REGISTRY:-"docker-ta.thinkingdata.cn"}
-  export GIT_REPO_HASH=$(md5sum $GIT_REPO_PKG | awk -F " " '{print $1}')
-  export GIT_DIR=/git/repo
+  echo "PLUGIN_DATA: ${PLUGIN_DATA}"
+  # HASH
+  export PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH=$(md5sum $PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG | awk -F " " '{print $1}')
+  export PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR=${PLUGIN_TA_MULTIVERSE_BUILD_DIR}/${PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH}
+  export PLUGIN_TA_MULTIVERSE_GIT_REPO_DIR=$PLUGIN_TA_MULTIVERSE_GIT_DIR/$PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH
 
-  export GIT_REPO_DIR=$GIT_DIR/$GIT_REPO_HASH
-  export BUILD_DIR=/build/flow/${GIT_REPO_HASH}
+  # PIPELINE
+  export PIPELINE_BUILD_CONTEXT=$PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR
+  export PIPELINE_GIT_REPOSITORY_DIR=$PLUGIN_TA_MULTIVERSE_GIT_REPO_DIR
+  export PIPELINE_DOCKER_REGISTRY=$PLUGIN_TA_MULTIVERSE_DOCKER_REGISTRY
+  export PIPELINE_IMAGE_NAME=$PLUGIN_TA_MULTIVERSE_GIT_REPO_NAME
+  export PIPELINE_IMAGE_TAGS=build_${PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH}
 
-  export PIPELINE_BUILD_CONTEXT=$BUILD_DIR
-  export PIPELINE_GIT_REPOSITORY_DIR=$GIT_REPO_DIR
-  export PIPELINE_DOCKER_REGISTRY=$DOCKER_REGISTRY
-  export PIPELINE_IMAGE_NAME=$GIT_REPO_NAME
-  export PIPELINE_IMAGE_TAGS=build_${GIT_REPO_HASH}
+  # EXPORT
+  export PLUGIN_TA_MULTIVERSE_RUNNER_NAME=zpipeline_${PLUGIN_TA_MULTIVERSE_GIT_REPO_HASH}
+  export PLUGIN_TA_MULTIVERSE_RUNNER_IMAGE=$PLUGIN_TA_MULTIVERSE_DOCKER_REGISTRY/$PIPELINE_IMAGE_NAME:$PIPELINE_IMAGE_TAGS
 
-  export RUNNER_NAME=zpipeline_${GIT_REPO_HASH}
-  export RUNNER_IMAGE=$DOCKER_REGISTRY/$PIPELINE_IMAGE_NAME:$PIPELINE_IMAGE_TAGS
+  if [ -z "$PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG" ]; then
+    log::info "PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG is required"
+    exit 1
+  fi
 
-  export EXPORT_DIR=${EXPORT_DIR:-"$BUILD_DIR/dist"}
+  if  [ ! -f "$PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG" ]; then
+    log::info "PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG($PLUGIN_TA_MULTIVERSE_GIT_REPO_PKG) is not a file"
+    exit 1
+  fi
 
-  mkdir -p $GIT_REPO_DIR
-  mkdir -p $BUILD_DIR
+  if [ -d "$PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR" ]; then
+    rm -rf $PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR
+  fi
+
+  mkdir -p $PLUGIN_TA_MULTIVERSE_GIT_REPO_DIR
+  # mkdir -p $PLUGIN_TA_MULTIVERSE_BUILD_ID_DIR
 }
 
 export -f ta-multiverse::prepare
