chore: add env PLUGIN_EUNOMIA_DOCKERFILES_DIR

diff --git a/config/config b/config/config
--- a/config/config
+++ b/config/config
@@ -4,6 +4,8 @@ export PLUGIN_EUNOMIA_GIT_DIR=${PLUGIN_DATA}/git/repo
 export PLUGIN_EUNOMIA_BUILD_DIR=${PLUGIN_DATA}/build
 export PLUGIN_EUNOMIA_PKG_DIR=${PLUGIN_DATA}/pkg
 export PLUGIN_EUNOMIA_EXPORT_DIR=${PLUGIN_DATA}/export
+# Dockerfiles
+export PLUGIN_EUNOMIA_DOCKERFILES_DIR=$${PLUGIN_DIR}/config/dockerfiles
 
 if [ ! -d "$PLUGIN_EUNOMIA_GIT_DIR" ]; then
   mkdir -p $PLUGIN_EUNOMIA_GIT_DIR
@@ -19,6 +21,16 @@ fi
 
 if [ ! -d "$PLUGIN_EUNOMIA_EXPORT_DIR" ]; then
   mkdir -p $PLUGIN_EUNOMIA_EXPORT_DIR
+fi
+
+if [ ! -d "$PLUGIN_EUNOMIA_DOCKERFILES_DIR" ]; then
+  log::error "[eunomia::build] Dockerfiles Dir($PLUGIN_EUNOMIA_DOCKERFILES_DIR) not found"
+  exit 1
+fi
+
+if [ -z "$(ls $PLUGIN_EUNOMIA_DOCKERFILES_DIR)" ]; then
+  log::error "[eunomia::build] Dockerfiles Dir($PLUGIN_EUNOMIA_DOCKERFILES_DIR) is empty"
+  exit 1
 fi
 
 
